
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "AS EXPORT FROM ID IMPORT STRING TABLEprogram : table_command\n| program table_commandtable_command : import_command\n| export_commandimport_command : IMPORT TABLE ID FROM STRING ';'export_command : EXPORT TABLE ID AS STRING ';'"
    
_lr_action_items = {'IMPORT':([0,1,2,3,4,7,16,17,],[5,5,-1,-3,-4,-2,-5,-6,]),'EXPORT':([0,1,2,3,4,7,16,17,],[6,6,-1,-3,-4,-2,-5,-6,]),'$end':([1,2,3,4,7,16,17,],[0,-1,-3,-4,-2,-5,-6,]),'TABLE':([5,6,],[8,9,]),'ID':([8,9,],[10,11,]),'FROM':([10,],[12,]),'AS':([11,],[13,]),'STRING':([12,13,],[14,15,]),';':([14,15,],[16,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'table_command':([0,1,],[2,7,]),'import_command':([0,1,],[3,3,]),'export_command':([0,1,],[4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> table_command','program',1,'p_program','parser.py',12),
  ('program -> program table_command','program',2,'p_program','parser.py',13),
  ('table_command -> import_command','table_command',1,'p_table_command','parser.py',17),
  ('table_command -> export_command','table_command',1,'p_table_command','parser.py',18),
  ('import_command -> IMPORT TABLE ID FROM STRING ;','import_command',6,'p_import_command','parser.py',22),
  ('export_command -> EXPORT TABLE ID AS STRING ;','export_command',6,'p_export_command','parser.py',27),
]
