
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "FROM ID IMPORT STRING TABLEprogram : table_command\n                   | table_command : import_command\n            | import_command : IMPORT TABLE ID FROM STRING ';'"
    
_lr_action_items = {'$end':([0,1,2,3,9,],[-2,0,-1,-3,-5,]),'IMPORT':([0,],[4,]),'TABLE':([4,],[5,]),'ID':([5,],[6,]),'FROM':([6,],[7,]),'STRING':([7,],[8,]),';':([8,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'table_command':([0,],[2,]),'import_command':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> table_command','program',1,'p_program','parser.py',12),
  ('program -> <empty>','program',0,'p_program','parser.py',13),
  ('table_command -> import_command','table_command',1,'p_table_command','parser.py',17),
  ('table_command -> <empty>','table_command',0,'p_table_command','parser.py',18),
  ('import_command -> IMPORT TABLE ID FROM STRING ;','import_command',6,'p_import_command','parser.py',22),
]
